### ISSUE TITLE
redirect helper : redirectResponse is ignored

### ISSUE THREAD

**Issue by puschie286** [bcit-ci/CodeIgniter4#1127] opened 2018-08-01 07:25 UTC
when using the redirect() helper function it use a "redirectResponse" which is not the same as the global response instance. so it will not work at all

simple calls to redirect()->route( 'Home' ) return an empty page with a 200 response code.

**Comment by lonnieezell** [comment] 2018-08-03 02:55
Are you returning the value? `return redirect()->xxx` worked fine last time I checked.

**Comment by puschie286** [comment] 2018-08-03 11:56
thats not working for me, because i dont use this function in the controller.

but good to know, thought codeigniter take care of using the right one.
Is there a reason for using a new instance ? cant imagine any situations that require a new response instance

**Comment by lonnieezell** [comment] 2018-08-03 13:37
Ah - well it's not designed to be used from within a library. The controllers are typically responsible for controlling application flow, not libraries. 

The `redirect()` method returns an instance of `RedirectResponse` not a normal `Response` class. 

If you must use it within a library (don't recommend it) have your controller type check it and, if it's a RedirectResponse class, return it, otherwise go about your duties. Preferred method is for the library to throw an exception, return failure, etc, and the controller checks that and makes the decision to redirect or not. 

Either way - not a bug. Closing.

**Closed by lonnieezell** 2018-08-03 13:37 UTC
