### ISSUE TITLE
Formatter for: "content-type: application/json"

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#977] opened 2018-03-31 01:55 UTC
I am trying to use CI4 for an API and I am sure that thing was working in some of previous versions. 

My request header is:
content-type:
application/json

I am getting error:

`<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: No Formatter defined for mime type:  in /home/.../site/application/Config/Format.php:56
Stack trace:
#0 /home/.../site/system/API/ResponseTrait.php(358): Config\Format-&gt;getFormatter('')
#1 /home/.../site/system/API/ResponseTrait.php(120): CodeIgniter\Debug\Exceptions-&gt;format(Array)
#2 /home/.../site/system/Debug/Exceptions.php(149): CodeIgniter\Debug\Exceptions-&gt;respond(Array, 500)
#3 [internal function]: CodeIgniter\Debug\Exceptions-&gt;exceptionHandler(Object(Error))
#4 {main}
  thrown in <b>/home/.../site/application/Config/Format.php</b> on line <b>56</b><br />
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: No Formatter defined for mime type:  in /home/.../site/application/Config/Format.php:56
Stack trace:
#0 /home/.../site/system/API/ResponseTrait.php(358): Config\Format-&gt;getFormatter('')
#1 /home/.../site/system/API/ResponseTrait.php(120): CodeIgniter\Debug\Exceptions-&gt;format(Array)
#2 /home/.../site/system/Debug/Exceptions.php(149): CodeIgniter\Debug\Exceptions-&gt;respond(Array, 500)
#3 /home/.../site/system/Debug/Exceptions.php(201): CodeIgniter\Debug\Exceptions-&gt;exceptionHandler(Object(ErrorException))
#4 [internal function]: CodeIgniter\Debug\Exceptions-&gt;shutdownHandler()
#5 {main}
  thrown in <b>/home/.../site/application/Config/Format.php</b> on line <b>56</b><br />`

When I add an print  $mime in this function it prints : undefined

**Comment by nowackipawel** [comment] 2018-03-31 04:15
I add 
'content-type:
application/json
accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
and post that package again, it was my fault with routes. Thx for hint, sorry for that, everything is working gr8.

**Comment by natanfelles** [comment] 2018-03-31 06:37
Oh, that's good you can solve.

Even so, it looks like we should do something to respond a generic format without the Accept Header. Checking the Content-Type also, maybe.

**Comment by nowackipawel** [comment] 2018-04-01 01:46
I think you could just look for other the most popular  content types provided by 'accept' header and return stack trace as JSON or XML. I think it will be the simplest improvement for that, I am not sure if it can be treated as issue.

**Comment by lonnieezell** [comment] 2018-04-21 03:44
@nowackipawel Could you provide steps to reproduce this from a new install? I just tried a GET request to the home page with no headers at all and it worked as expected.

**Comment by lonnieezell** [comment] 2018-06-01 13:28
Glad to hear it's working now! Closing.

**Closed by lonnieezell** 2018-06-01 13:28 UTC
