### ISSUE TITLE
Cookie not working

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#1057] opened 2018-05-30 08:15 UTC
After the last update on the respond class, the cookie does not work. 
I tried to fix the issue using array_values which stops the error, but the cookie still wouldn't set. 
The image attached below, is the error that occurs. 

![img_20180530_091145](https://user-images.githubusercontent.com/621320/40707920-f2116046-63e9-11e8-9975-db13a33edbc9.jpg)

**Comment by albertleao** [comment] 2018-05-30 21:14
It's really preferred that you past your error so it's searchable and easier to read. A picture of your monitor really makes it hard especially with line numbers and the full message being cut off.

**Comment by dayrui** [comment] 2018-06-05 10:45
`		foreach ($this->cookies as $params)
		{
            call_user_func_array('setcookie', $params);
			//setcookie(...$params);
		}
	}`
/System/HTTP/Response.php

**Comment by chistel** [comment] 2018-06-05 12:49
this works, but when i use cookies in remember me, the cookies does not work.

**Comment by dayrui** [comment] 2018-06-05 15:32
So am I

**Comment by dayrui** [comment] 2018-06-05 15:33
@lonnieezell

**Comment by lonnieezell** [comment] 2018-06-06 16:15
I'll try to look into this tonight. Can someone post the example code they're using to recreate, just to verify there's nothing wrong there or with the docs?

**Comment by chistel** [comment] 2018-06-06 18:39
@lonniel using the cookies within a normal controller works with correction by @dayrui but when I use it for authentication remember me feature, the cookie never set.  I would share my code usage once I switch to PC.  earlier today I moved the sendCookie method form the send respond into the setcookie method, and it worked well.

**Comment by lonnieezell** [comment] 2018-06-07 03:04
Well, without seeing code there's no way for me to know what's different between your "remember me" code and the controller usage. There's a lot of variables that _could_ make it user error and not a bug, and that's what we have to determine. :)  I'll look into the other change now, though.

**Comment by lonnieezell** [comment] 2018-06-07 03:59
And.... reading the initial error solved it :) I've pushed up a fix for this.

**Closed** 2018-06-07 03:58 UTC
