### ISSUE TITLE
$baseUrl problem with Router

### ISSUE THREAD

**Issue by ridho1991** [bcit-ci/CodeIgniter4#238] opened 2016-08-20 04:51 UTC
I have function like this:
public function testpage()
{
	echo 'this is a test page';
}

And added a route like this:
$routes->add('testpage', 'Home::testpage');

When I leave $baseUrl blank, then I access http://ci4.local/testpage, it show the page.
But when I set $baseUrl='http://ci4.local/', then I access http://ci4.local/testpage, it show default CI4 welcome page. 
Even I try random uri like http://ci4.local/fdgfdgfdg, it also show default CI4 welcome page instead of 404 error page.

So I think this is a bug that must be solved as soon as possible.

**Comment by lonnieezell** [comment] 2016-08-20 05:09
What does your routes file look like, including the various settings in routes.php?

**Comment by ridho1991** [comment] 2016-08-20 05:38
I use default router settings, then I added this line:
$routes->add('testpage', 'Home::testpage');

**Comment by DavisMiculis** [comment] 2016-08-20 14:58
I can confirm that setting `$baseUrl = '';` and leave it to automatically find the domain path works good. Setting to anything else, for example `$baseUrl = 'http://ci4.local/` only shows the default homepage on every page.

Also note on routing that absolute paths doesn't work correctly.

Example:

Code in Routes.php:
```
$routes->get('/profile/change-email', 'Profile::changeEmail', ['as' => 'change-email']);
```

Code in a view file:
```
<a href="<?= route_to('change-email') ?>">Change Email</a>
```

When clicked on link, shows:
```
Call to undefined method App\Controllers\Profile::change-email()
```

It uses the `as` name for controller method, although it should use the `Profile::changeEmail`

---

I currently use URLs without leading slashes, and hard-code them in views, because if I open `/profile/` then click on link, it goes to `/profile/profile/change-email`.

Current code that works for me:

Code in Routes.php:
```
$routes->get('profile/change-email', 'Profile::changeEmail', ['as' => 'change-email']);
```

Code in a view file:
```
<a href="/<?= route_to('change-email') ?>">Change Email</a>
```

Works as indented, but I don't know which one should be fixed, the Routing or the `route_to()` function.

**Comment by lonnieezell** [comment] 2016-08-22 03:47
The OP's problem should now be fixed. Thanks for reporting it. 

@DavisMiculis could you open a new issue for the other problem you're seeing? Too hard to keep things straight with multiple issues in the same post.

**Closed by lonnieezell** 2016-08-22 03:47 UTC

**Comment by ridho1991** [comment] 2016-08-22 05:02
You're welcome.
