### ISSUE TITLE
Redirects to wrong incomplete URL

### ISSUE THREAD

**Issue by JefteCaro** [bcit-ci/CodeIgniter4#710] opened 2017-09-07 03:24 UTC
Using these URL works fine:
```php
http://localhost/ci4/public/index.php/home
http://localhost/ci4/public/index.php
```
since I installed in a sub directory `ci4/public`

but when I used this URL,
```php
http://localhost/ci4/public/index.php/
```
it redirects to
```php
http://localhost/index.php
```

tried to set
```php
public $baseURL = 'http://localhost/ci4/public/';
```
in 
```php
application/Config/App.php
```
but still redirects to the said URL.

**Comment by lonnieezell** [comment] 2017-09-07 03:53
This is most likely due to the default .htaccess file in the `public` folder, which, by default, will redirect to /index.php when a URL is not found. Modify the `RewriteBase` in that file and you should be good. 

Closing this since this is not a bug in the software. If you need additional help, please visit the forums and ask there.

**Closed by lonnieezell** 2017-09-07 03:53 UTC
